services:
  gymhub_db:
    image: postgres:17

    container_name: gymhub-postgres

    environment:
      POSTGRES_DB: gymhub
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "6543:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: