services:
  postgres:
    image: postgres:17

    container_name: gymhub-postgres

    environment:
      POSTGRES_DB: gymhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "6543:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: