ALTER TABLE users
    ADD COLUMN last_name VARCHAR(100),
    ADD COLUMN phone VARCHAR(20),
    ADD COLUMN birth_day DATE NOT NULL,
    ADD COLUMN city VARCHAR(100) NOT NULL,
    ADD COLUMN created TIMESTAMP NOT NULL;